### ISSUE TITLE
Failed to activate the file-icon-supplement package

### ISSUE THREAD

**Issue by charlynet7** [sscotth/file-icon-supplement#12]
[Enter steps to reproduce below:]

It appears when Atom start.

**Atom Version**: 0.194.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [file-icon-supplement](https://github.com/sscotth/file-icon-supplement) package, v0.7.8

### Stack Trace

Failed to activate the file-icon-supplement package

```
At Cannot find module 'underscore-plus'

Error: Cannot find module 'underscore-plus'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (C:\Users\<user>\AppData\Local\atom\app-0.194.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/C:/Users/<user>/.atom/packages/file-icon-supplement/lib/file-icon-supplement-view.coffee:10:7)
    at Object.<anonymous> (/C:/Users/<user>/.atom/packages/file-icon-supplement/lib/file-icon-supplement-view.coffee:448:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (C:\Users\<user>\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "data-atom",
      "save-session",
      "vim-mode"
    ],
    "themes": [
      "seti-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
block-cursor, v0.12.4
compare-files, v0.4.1
file-icon-supplement, v0.7.8
highlight-line, v0.10.2
highlight-selected, v0.9.2
language-batch, v0.3.2
minimap, v4.7.6
minimap-find-and-replace, v4.2.0
minimap-highlight-selected, v4.2.1
minimap-selection, v4.2.0
seti-ui, v0.6.3

# Dev
No dev packages
```

**Comment by sscotth** [comment]
Thanks for posting. It looks like the underscore-plus module was missing from the package.json

Should be fixed in https://github.com/sscotth/file-icon-supplement/commit/9488e5a046627380e511956d55016eeabed050bc and in v0.7.9
