### ISSUE TITLE
Uncaught Error: Unable to watch path

### ISSUE THREAD

**Issue by TizzyD** [sscotth/file-icon-supplement#21]
Steps to produce error:

1. Updated the Atom application via the menu item, selecting to install update and restart.
2. Upon restart, error displays.

**Atom Version**: 1.0.2
**System**: Mac OS X 10.11
**Thrown From**: [file-icon-supplement](https://github.com/sscotth/file-icon-supplement) package, v0.8.3

### Stack Trace

Uncaught Error: Unable to watch path

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:66

Error: Unable to watch path
    at Error (native)
    at HandleWatcher.start (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:66:29)
    at new HandleWatcher (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:30:12)
    at new PathWatcher (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:120:30)
    at Object.exports.watch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:179:12)
    at Directory.module.exports.Directory.subscribeToNativeChangeEvents (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/directory.js:334:109)
    at Directory.module.exports.Directory.willAddSubscription (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/directory.js:95:14)
    at Directory.willAddSubscription (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/directory.js:3:61)
    at Directory.module.exports.Directory.onDidChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/directory.js:89:12)
    at /Volumes/Is/tizzyd/.atom/packages/file-icon-supplement/lib/file-icon-supplement-view.coffee:216:23
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "unity-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
aligner-css, v1.2.0
aligner-php, v1.0.0
aligner-ruby, v1.4.0
aligner-scss, v1.0.1
atom-ternjs, v0.6.7
autoclose-html, v0.18.0
autocomplete-php, v0.3.6
autocomplete-plus-python-jedi, v0.3.6
color-picker, v2.0.7
csslint, v1.1.3
docblockr, v0.7.2
emmet, v2.3.11
file-icon-supplement, v0.8.3
file-icons, v1.5.8
hex, v0.6.2
highlight-line, v0.11.0
highlight-selected, v0.10.1
htmlhint, v1.1.3
jshint, v1.3.8
linter, v1.1.0
linter-csslint, v0.0.14
linter-htmlhint, v0.0.16
linter-js-yaml, v1.1.1
linter-jshint, v0.1.7
linter-php, v0.0.15
linter-phpcs, v0.0.15
linter-phpmd, v0.0.11
linter-scss-lint, v1.0.5
linter-tidy, v1.0.1
local-history, v3.2.3
minimap, v4.10.1
project-manager, v1.15.10
save-session, v0.15.6
unity-ui, v2.0.11
wordpress-api, v1.2.1

# Dev
No dev packages
```

**Comment by sscotth** [comment]
Thanks for the report. Does this error occur when you open a project, or just the atom editor? If so, what is the path? Also, is your file system case sensitive?

I don't see an issue in atom/pathwatcher, but my initial guesses are something in OSX 10.11 beta, an issue with the path/file system, or another plugin. I will try and recreate your issue in a VM.
