### ISSUE TITLE
Uncaught TypeError: Arguments to CompositeDisposable.add must have a .dispose() method

### ISSUE THREAD

**Issue by errok** [sscotth/file-icon-supplement#29]
on atom open with folder open

**Atom Version**: 1.11.1
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [file-icon-supplement](https://github.com/sscotth/file-icon-supplement) package, v0.8.3

### Stack Trace

Uncaught TypeError: Arguments to CompositeDisposable.add must have a .dispose() method

```
At /Users/user/Documents/Program/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:70

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (/Users/user/Documents/Program/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:70:13)
    at CompositeDisposable.module.exports.CompositeDisposable.add (/Users/user/Documents/Program/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:43:11)
    at FileIconSupplementView.module.exports.FileIconSupplementView.handleEvents (/Users/user/.atom/packages/file-icon-supplement/lib/file-icon-supplement-view.coffee:60:20)
    at /Users/user/.atom/packages/file-icon-supplement/lib/file-icon-supplement-view.coffee:15:8
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "packagesWithKeymapsDisabled": [
      "toggle-quotes"
    ]
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.22.2 (active)
angularjs, v0.3.5 (active)
atom-beautify, v0.29.13 (inactive)
atom-quoteswap, v0.4.6 (active)
autoclose-html, v0.23.0 (active)
emmet, v2.4.3 (active)
file-icon-supplement, v0.8.3 (active)
git-blame, v0.4.11 (inactive)
highlight-selected, v0.11.2 (active)
jshint, v1.8.6 (active)
linter, v1.11.18 (active)
linter-json-lint, v0.1.1 (active)
markdown-preview-plus, v2.4.0 (active)
minimap, v4.25.0 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-highlight-selected, v4.4.0 (active)
open-recent, v5.0.0 (active)
pigments, v0.37.0 (active)
pretty-json, v1.6.1 (active)
rest-client, v1.2.6 (active)
simple-align, v0.2.0 (inactive)
sort-lines, v0.14.0 (inactive)
toggle-quotes, v1.0.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by mikeerickson** [comment]
+1

**Comment by deadsunrise** [comment]
+1

**Comment by ccaroon** [comment]
+1

**Comment by flyinbutrs** [comment]
+1

**Comment by cbcoutinho** [comment]
+1
