### ISSUE TITLE
Uncaught TypeError: Cannot read property 'resultsModel' of null

### ISSUE THREAD

**Issue by stevenecollins** [sscotth/file-icon-supplement#8]
Uncaught TypeError: Cannot read property 'resultsModel' of null

**Atom Version**: 0.158.0
**System**: Mac OS X 10.10.1
**Thrown From**: [file-icon-supplement](https://github.com/sscotth/file-icon-supplement) package, v0.7.2

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /Users/steven/.atom/packages/file-icon-supplement/lib/file-icon-supplement-view.coffee:163

TypeError: Cannot read property 'resultsModel' of null
  at FileIconSupplementView.module.exports.FileIconSupplementView.removeFindAndReplaceEvent (/Users/steven/.atom/packages/file-icon-supplement/lib/file-icon-supplement-view.coffee:164:19)
  at FileIconSupplementView.module.exports.FileIconSupplementView.loadFindAndReplaceSettings (/Users/steven/.atom/packages/file-icon-supplement/lib/file-icon-supplement-view.coffee:152:8)
  at /Users/steven/.atom/packages/file-icon-supplement/lib/file-icon-supplement-view.coffee:58:11
  at /Applications/Atom.app/Contents/Resources/app/src/config.js:571:20
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app/src/config.js:556:29)
  at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app/src/config.js:189:14)
  at FileIconSupplementView.module.exports.FileIconSupplementView.disableAllSettings (/Users/steven/.atom/packages/file-icon-supplement/lib/file-icon-supplement-view.coffee:248:17)
  at FileIconSupplementView.module.exports.FileIconSupplementView.toggleClass (/Users/steven/.atom/packages/file-icon-supplement/lib/file-icon-supplement-view.coffee:216:8)
  at atom-workspace.<anonymous> (/Users/steven/.atom/packages/file-icon-supplement/lib/file-icon-supplement-view.coffee:49:11)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:112:34)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at [object Object].jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:64:23)
  at Ipc.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:70:67)
  at Ipc.emit (events.js:110:17)
  at process.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:118:17)
  at Ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:39:29)
  at Ipc.sendChannelSync (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:47:28)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app/src/context-menu-manager.js:169:33)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:138:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

/cc @atom/core

**Comment by sscotth** [comment]
Cannot Reproduce
